@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyNTYxMzk1NywianRpIjoiYWZmMzZmNGQtMjRiMi00NDE3LTlkMjItMDVjMWE5ZmFiZWExIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJhaHVsQGdtYWlsLmNvbSIsIm5iZiI6MTcyNTYxMzk1NywiY3NyZiI6IjdmNjllZjA1LTQyMmUtNDIzNy04NzdjLTE0YWFiZTQ2MDRhOCIsImV4cCI6MTcyNTYxNDg1N30.F6DenGUSJooXNsqi8ZO2spx7N5LmDMdUwm0D35pb9LY



// User Management

// Login using below api and copy accss_token from response and pass it to above @token variable to pass dynamic token to all api.
###
POST  http://127.0.0.1:5000/auth/login
Content-Type: application/json

{
	"email": "rahul@gmail.com",
	"password": "123456"
}

###
POST  http://127.0.0.1:5000/auth/register
Content-Type: application/json

{
	"username": "Shivam",
	"email": "shivam@gmail.com",
	"contact_no": "9854120017",
	"password": "123456"
}


###
# GET  http://localhost:5134/assign/get
# Authorization: Bearer {{token}}
# Content-Type: application/json

###
GET  http://127.0.0.1:5000/admin/get/users
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  http://127.0.0.1:5000/auth/get/users/master-data
Authorization: Bearer {{token}}
Content-Type: application/json

// Professionals

###
POST  http://127.0.0.1:5000/auth/add/user/professional-details
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"designation": "Web Dev",
	"prev_experience": "12",
	"experience": "24",
	"salary": "10000",
	"skills": "html,css,js",
	"cv_intro": "This is Demo Intro",
	"joining_date": "12-08-2024",
	"permanent_confirm_date": "05-07-2023",
	"termination_date": "",
	"termination_reason": "",
	"user_id": "2"
}

###
PUT  http://127.0.0.1:5000/auth/update/user/professional-details/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"designation": "Web Dev",
	"prev_experience": "12",
	"experience": "24",
	"salary": "10000",
	"skills": "html,css,js",
	"cv_intro": "This is Demo Intro",
	"joining_date": "12-08-2024",
	"permanent_confirm_date": "05-07-2023",
	"termination_date": "",
	"termination_reason": "",
	"user_id": "2"
}

###
GET  http://127.0.0.1:5000/auth/get/all-users/professional/list
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  http://127.0.0.1:5000/auth/get/user/professional-details/1
Authorization: Bearer {{token}}
Content-Type: application/json

###
DELETE  http://127.0.0.1:5000/auth/professionals/1
Authorization: Bearer {{token}}
Content-Type: application/json


// Personals

###
POST  http://127.0.0.1:5000/auth/add/user/personal-details
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"src": "asdfsdfsd",
	"gender": "Male",
	"dob": "2008-05-15",
	"bio": "Demo Bio",
	"address": "Malad station",
	"address2": "demo",
	"state": "goa",
	"city": "mumbai",
	"zipcode": "400099",
	"country": "india",
	"address_type": "permanent",
	"user_id": "2"
}

###
PUT  http://127.0.0.1:5000/auth/update/user/personal-details/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"src": "asdfsdfsd",
	"gender": "Male",
	"dob": "2008-05-15",
	"bio": "Demo Bio",
	"address": "Malad station",
	"address2": "demo",
	"state": "goa",
	"city": "mumbai",
	"zipcode": "400099",
	"country": "india",
	"address_type": "permanent",
	"user_id": "2"
}

###
GET  http://127.0.0.1:5000/auth/get/all-users/personal/list
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  http://127.0.0.1:5000/auth/get/user/personal-details/1
Authorization: Bearer {{token}}
Content-Type: application/json

###
DELETE  http://127.0.0.1:5000/auth/delete/user/personal-details/1
Authorization: Bearer {{token}}
Content-Type: application/json



// Educations

###
POST  http://127.0.0.1:5000/auth/add/user/education-details
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"university_name": "Mumbai",
	"course_name": "SSC",
	"start_date": "10-06-2012",
	"end_date": "10-06-2013",
	"grade": "50",
	"user_id": "2"
	
}
###
PUT  http://127.0.0.1:5000/auth/update/user/education-details/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"university_name": "Mumbai",
	"course_name": "SSC",
	"start_date": "10-06-2012",
	"end_date": "10-06-2013",
	"grade": "50",
	"user_id": "2"
	
}

###
GET  http://127.0.0.1:5000/auth/get/all-users/education/list
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  http://127.0.0.1:5000/auth/get/user/education-details/1
Authorization: Bearer {{token}}
Content-Type: application/json

###
DELETE  http://127.0.0.1:5000/auth/delete/user/personal-details/3
Authorization: Bearer {{token}}
Content-Type: application/json


// Banks

###
POST  http://127.0.0.1:5000/auth/add/user/bank-details
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"bank_name": "Hdfc",
	"account_no": "9854125478",
	"ifsc_code": "45621456874",
	"branch_name": "Vashi",
	"bank_address": "Vashi Station",
	"pan_card": "1236547858",
	"aadhar_card": "985415785",
	"aadhar_img": "sadfsdfsd",
	"pan_img": "asdsdfsdf",
	"bank_passbook_img": "asdsdasd",
	"user_id": "3"
	
}

###
PUT  http://127.0.0.1:5000/auth/update/user/bank-details/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"bank_name": "Hdfc",
	"account_no": "9854125478",
	"ifsc_code": "45621456874",
	"branch_name": "Vashi",
	"bank_address": "Vashi Station",
	"pan_card": "1236547858",
	"aadhar_card": "985415785",
	"aadhar_img": "sadfsdfsd",
	"pan_img": "asdsdfsdf",
	"bank_passbook_img": "asdsdasd",
	"user_id": "2"
	
}

###
GET  http://127.0.0.1:5000/auth/get/all-users/bank/list
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  http://127.0.0.1:5000/auth/get/user/bank-details/2
Authorization: Bearer {{token}}
Content-Type: application/json

###
DELETE  http://127.0.0.1:5000/auth/delete/user/bank-details/2
Authorization: Bearer {{token}}
Content-Type: application/json



// office location api's

###
POST  http://127.0.0.1:5000/auth/add/office/location
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"office_location": "Sanpada G-square ",
	"latitude": "19.06",
	"longitude": "73.00"
	
}

###
PUT  http://127.0.0.1:5000/auth/update/office/location/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"office_location": "Sanpada G-square ",
	"latitude": "19.066",
	"longitude": "73.00"
	
}

###
GET  http://127.0.0.1:5000/auth/get/all-office-location/list
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  http://127.0.0.1:5000/auth/get/office/location/1
Authorization: Bearer {{token}}
Content-Type: application/json

###
DELETE  http://127.0.0.1:5000/auth/delete/office/location/2
Authorization: Bearer {{token}}
Content-Type: application/json


// family api's

###
POST  http://127.0.0.1:5000/auth/add/user/family-details
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"father_name": "Test f name",
	"mother_name": "Test m name",
	"personal_email": "tys@gmail.com",
	"alternate_contact": "9985412012",
	"family_address": "Vashi Station",
	"user_id": "1"
	
}

###
PUT  http://127.0.0.1:5000/auth/update/user/family-details/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"father_name": "Test f name",
	"mother_name": "Test m name",
	"personal_email": "tys@gmail.com",
	"alternate_contact": "9985412012",
	"family_address": "Vashi Station",
	"user_id": "1"
	
}

###
GET  http://127.0.0.1:5000/auth/get/all-users/family/list
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  http://127.0.0.1:5000/auth/get/user/family-details/2
Authorization: Bearer {{token}}
Content-Type: application/json

###
DELETE  http://127.0.0.1:5000/auth/delete/user/family-details/2
Authorization: Bearer {{token}}
Content-Type: application/json


// project api's

###
POST  http://127.0.0.1:5000/auth/add/user/project-details
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"title": "Hrms app",
	"description": "Test hrms app",
	"start_date": "2022-05-15",
	"end_date": "2022-09-15",
	"user_id": "1"
	
}

###
PUT  http://127.0.0.1:5000/auth/update/user/project-details/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"title": "Hrms app",
	"description": "Test hrms app",
	"start_date": "2022-05-15",
	"end_date": "2022-09-15",
	"user_id": "1"
	
}

###
GET  http://127.0.0.1:5000/auth/get/all-users/project/list
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  http://127.0.0.1:5000/auth/get/user/project-details/1
Authorization: Bearer {{token}}
Content-Type: application/json

###
DELETE  http://127.0.0.1:5000/auth/delete/user/project-details/2
Authorization: Bearer {{token}}
Content-Type: application/json
