@appUrl = https://tys-hrms-app.onrender.com
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczMTMxMDgwOSwianRpIjoiNWFlYzczZjItMDA1Yy00MmE2LWE3ZmYtNmY2OTA5ZWI0OWZmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJ1c2VyX2lkIjozLCJlbWFpbCI6InNhbmpheUBnbWFpbC5jb20ifSwibmJmIjoxNzMxMzEwODA5LCJjc3JmIjoiNGI5ODhhNGQtZmYzOS00ZjQxLWI4ZWYtZmE4OWRhOWYxMjNhIiwiZXhwIjoxNzMxMzk3MjA5fQ.XV3dETd3n6v_2gUYtBJuxCQs16YE2RpKGUJb9cteamE



// User Management

// Login using below api and copy accss_token from response and pass it to above @token variable to pass dynamic token to all api.
###
POST  {{appUrl}}/auth/login
Content-Type: application/json

{
	"email": "sanjay@gmail.com",
	"password": "123456"
}

###
POST  {{appUrl}}/auth/register
Content-Type: application/json

{
	"username": "ajay",
	"email": "ajay@gmail.com",
	"contact_no": "9854125478",
	"password": "123456"
}

###
GET  {{appUrl}}/admin/get/users
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET {{appUrl}}/auth/user/1
Authorization: Bearer {{token}}
Content-Type: application/json

###
PUT {{appUrl}}/auth/user/edit/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"username": "Sanket Hemade",
	"email": "sanket@gmail.com",
	"contact_no": "9854120013"
}

###
PUT {{appUrl}}/auth/user/reset-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"email": "sanket@gmail.com",
	"password": "123456"
}

###
PUT {{appUrl}}/admin/update/user-status/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "status": 0
}

###
DELETE  {{appUrl}}/admin/delete/user/3
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  {{appUrl}}/auth/get/users/master-data
Authorization: Bearer {{token}}
Content-Type: application/json


// Role Management

###
POST  {{appUrl}}/auth/add/user/role
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"name": "Emp"
}

###
POST  {{appUrl}}/auth/add/user/permission
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"name": "Delete"
}

###
POST  {{appUrl}}/auth/assign/user/permission/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"permission_ids": "4,5"
}

###
POST  {{appUrl}}/auth/assign/user/role
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "user_id": 1,
  "role_id": 1
}

###
GET  {{appUrl}}/auth/get/user/roles-list
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  {{appUrl}}/auth/get/user/permissions
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  {{appUrl}}/auth/get/user/assigned-roles
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  {{appUrl}}/auth/get/assigned/user-roles
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  {{appUrl}}/auth/get/assigned/user-role/1
Authorization: Bearer {{token}}
Content-Type: application/json

// Professionals

###
POST  {{appUrl}}/auth/add/user/professional-details
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"designation": "Web Dev",
	"prev_experience": "12",
	"experience": "24",
	"salary": "10000",
	"skills": "html,css,js",
	"cv_intro": "This is Demo Intro",
	"joining_date": "12-08-2024",
	"permanent_confirm_date": "05-07-2023",
	"termination_date": "",
	"termination_reason": "",
	"user_id": "2"
}

###
PUT  {{appUrl}}/auth/update/user/professional-details/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"designation": "Web Dev",
	"prev_experience": "12",
	"experience": "24",
	"salary": "10000",
	"skills": "html,css,js",
	"cv_intro": "This is Demo Intro",
	"joining_date": "12-08-2024",
	"permanent_confirm_date": "05-07-2023",
	"termination_date": "",
	"termination_reason": "",
	"user_id": "2"
}

###
GET  {{appUrl}}/auth/get/all-users/professional/list
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  {{appUrl}}/auth/get/user/professional-details/1
Authorization: Bearer {{token}}
Content-Type: application/json

###
DELETE  {{appUrl}}/auth/professionals/1
Authorization: Bearer {{token}}
Content-Type: application/json


// Personals

###
POST  {{appUrl}}/auth/add/user/personal-details
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"src": "asdfsdfsd",
	"gender": "Male",
	"dob": "2008-05-15",
	"bio": "Demo Bio",
	"address": "Malad station",
	"address2": "demo",
	"state": "goa",
	"city": "mumbai",
	"zipcode": "400099",
	"country": "india",
	"address_type": "permanent",
	"user_id": "2"
}

###
PUT  {{appUrl}}/auth/update/user/personal-details/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"src": "asdfsdfsd",
	"gender": "Male",
	"dob": "2008-05-15",
	"bio": "Demo Bio",
	"address": "Malad station",
	"address2": "demo",
	"state": "goa",
	"city": "mumbai",
	"zipcode": "400099",
	"country": "india",
	"address_type": "permanent",
	"user_id": "2"
}

###
GET  {{appUrl}}/auth/get/all-users/personal/list
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  {{appUrl}}/auth/get/user/personal-details/1
Authorization: Bearer {{token}}
Content-Type: application/json

###
DELETE  {{appUrl}}/auth/delete/user/personal-details/1
Authorization: Bearer {{token}}
Content-Type: application/json



// Educations

###
POST  {{appUrl}}/auth/add/user/education-details
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"university_name": "Mumbai",
	"course_name": "SSC 2",
	"start_date": "10-06-2012",
	"end_date": "10-06-2013",
	"grade": "50",
	"user_id": "3"
	
}
###
PUT  {{appUrl}}/auth/update/user/education-details/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"university_name": "Mumbai",
	"course_name": "SSC",
	"start_date": "10-06-2012",
	"end_date": "10-06-2013",
	"grade": "50",
	"user_id": "2"
	
}

###
GET  {{appUrl}}/auth/get/all-users/education/list
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  {{appUrl}}/auth/get/user/education-list/3
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  {{appUrl}}/auth/get/user/education-details/3
Authorization: Bearer {{token}}
Content-Type: application/json

###
DELETE  {{appUrl}}/auth/delete/user/personal-details/3
Authorization: Bearer {{token}}
Content-Type: application/json


// Banks

###
POST  {{appUrl}}/auth/add/user/bank-details
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"bank_name": "Hdfc",
	"account_no": "9854125478",
	"ifsc_code": "45621456874",
	"branch_name": "Vashi",
	"bank_address": "Vashi Station",
	"pan_card": "1236547858",
	"aadhar_card": "985415785",
	"aadhar_img": "sadfsdfsd",
	"pan_img": "asdsdfsdf",
	"bank_passbook_img": "asdsdasd",
	"user_id": "3"
	
}

###
PUT  {{appUrl}}/auth/update/user/bank-details/2
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"bank_name": "Hdfc",
	"account_no": "9854125478",
	"ifsc_code": "45621456874",
	"branch_name": "Vashi",
	"bank_address": "Vashi Station",
	"pan_card": "1236547858",
	"aadhar_card": "985415785",
	"aadhar_img": "sadfsdfsd",
	"pan_img": "asdsdfsdf",
	"bank_passbook_img": "asdsdasd",
	"user_id": "2"
	
}

###
GET  {{appUrl}}/auth/get/all-users/bank/list
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  {{appUrl}}/auth/get/user/bank-details/2
Authorization: Bearer {{token}}
Content-Type: application/json

###
DELETE  {{appUrl}}/auth/delete/user/bank-details/2
Authorization: Bearer {{token}}
Content-Type: application/json



// office location api's

###
POST  {{appUrl}}/auth/add/office/location
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"office_location": "Sanpada G-square ",
	"latitude": "19.06",
	"longitude": "73.00"
	
}

###
PUT  {{appUrl}}/auth/update/office/location/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"office_location": "Sanpada G-square ",
	"latitude": "19.066",
	"longitude": "73.00"
	
}

###
GET  {{appUrl}}/auth/get/all-office-location/list
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  {{appUrl}}/auth/get/office/location/1
Authorization: Bearer {{token}}
Content-Type: application/json

###
DELETE  {{appUrl}}/auth/delete/office/location/2
Authorization: Bearer {{token}}
Content-Type: application/json


// family api's

###
POST  {{appUrl}}/auth/add/user/family-details
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"father_name": "Test f name",
	"mother_name": "Test m name",
	"personal_email": "tys@gmail.com",
	"alternate_contact": "9985412012",
	"family_address": "Vashi Station",
	"user_id": "1"
	
}

###
PUT  {{appUrl}}/auth/update/user/family-details/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"father_name": "Test f name",
	"mother_name": "Test m name",
	"personal_email": "tys@gmail.com",
	"alternate_contact": "9985412012",
	"family_address": "Vashi Station",
	"user_id": "1"
	
}

###
GET  {{appUrl}}/auth/get/all-users/family/list
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  {{appUrl}}/auth/get/user/family-details/2
Authorization: Bearer {{token}}
Content-Type: application/json

###
DELETE  {{appUrl}}/auth/delete/user/family-details/2
Authorization: Bearer {{token}}
Content-Type: application/json


// project api's

###
POST  {{appUrl}}/auth/add/user/project-details
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"title": "Hrms app",
	"description": "Test hrms app",
	"start_date": "2022-05-15",
	"end_date": "2022-09-15",
	"user_id": "1"
	
}

###
PUT  {{appUrl}}/auth/update/user/project-details/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"title": "Hrms app",
	"description": "Test hrms app",
	"start_date": "2022-05-15",
	"end_date": "2022-09-15",
	"user_id": "1"
	
}

###
GET  {{appUrl}}/auth/get/all-users/project/list
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  {{appUrl}}/auth/get/user/project-details/1
Authorization: Bearer {{token}}
Content-Type: application/json

###
DELETE  {{appUrl}}/auth/delete/user/project-details/2
Authorization: Bearer {{token}}
Content-Type: application/json


// Attendance api's

###
POST  {{appUrl}}/auth/add/user/attendance
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"email": "sanjay@gmail.com",
	"coordinate": "0",
	"current_address": "0"
	
}

###
GET  {{appUrl}}/auth/get/all-users/attendances-list?month=November&year=2024

Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  {{appUrl}}/auth/get/user/todays-attendance
Authorization: Bearer {{token}}
Content-Type: application/json

###
GET  {{appUrl}}/auth/get/user/attendance/3?month=November&year=2024

Authorization: Bearer {{token}}
Content-Type: application/json

###
DELETE  {{appUrl}}/auth/delete/user/attendance/1
Authorization: Bearer {{token}}
Content-Type: application/json

