"""Added Bank model

Revision ID: 7c9d09383379
Revises: 866dbf027aed
Create Date: 2024-09-03 10:29:13.267105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9d09383379'
down_revision = '866dbf027aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=True),
    sa.Column('account_no', sa.String(length=255), nullable=True),
    sa.Column('ifsc_code', sa.String(length=255), nullable=True),
    sa.Column('branch_name', sa.String(length=255), nullable=True),
    sa.Column('bank_address', sa.String(length=255), nullable=True),
    sa.Column('pan_card', sa.String(length=255), nullable=True),
    sa.Column('aadhar_card', sa.String(length=255), nullable=True),
    sa.Column('aadhar_img', sa.String(length=255), nullable=True),
    sa.Column('pan_img', sa.String(length=255), nullable=True),
    sa.Column('bank_passbook_img', sa.String(length=255), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True, comment='0: Approved, 1: Pending, 2: Rejected'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_name', sa.String(length=255), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.String(length=80), nullable=False),
    sa.Column('end_date', sa.String(length=80), nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('src', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('bio', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('address2', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('zipcode', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('address_type', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personal')
    op.drop_table('education')
    op.drop_table('bank')
    # ### end Alembic commands ###
