"""Added Professional model

Revision ID: 866dbf027aed
Revises: e098346d63d6
Create Date: 2024-09-02 19:06:10.010734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866dbf027aed'
down_revision = 'e098346d63d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=80), nullable=False),
    sa.Column('prev_experience', sa.String(length=80), nullable=True),
    sa.Column('experience', sa.String(length=80), nullable=True),
    sa.Column('salary', sa.BigInteger(), nullable=True),
    sa.Column('skills', sa.String(length=255), nullable=True),
    sa.Column('cv_intro', sa.String(length=255), nullable=True),
    sa.Column('joining_date', sa.String(length=80), nullable=True),
    sa.Column('permanent_confirm_date', sa.String(length=80), nullable=True),
    sa.Column('termination_date', sa.String(length=80), nullable=True),
    sa.Column('termination_reason', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professional')
    # ### end Alembic commands ###
