"""empty message

Revision ID: e1ca35d6724d
Revises: 08a0cdfd407d
Create Date: 2024-09-09 12:55:57.274356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ca35d6724d'
down_revision = '08a0cdfd407d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('attendance_year', sa.Integer(), nullable=True),
    sa.Column('attendance_month', sa.String(length=255), nullable=True),
    sa.Column('attendance_date', sa.Date(), nullable=True),
    sa.Column('attendance_day', sa.String(length=255), nullable=True),
    sa.Column('attendance_status', sa.String(length=255), nullable=True),
    sa.Column('holiday', sa.String(length=255), nullable=True),
    sa.Column('is_applied', sa.String(length=255), nullable=True),
    sa.Column('in_time', sa.Time(), nullable=True),
    sa.Column('out_time', sa.Time(), nullable=True),
    sa.Column('total_hours', sa.String(length=255), nullable=True),
    sa.Column('is_late', sa.Boolean(), nullable=True),
    sa.Column('current_address', sa.String(length=255), nullable=True),
    sa.Column('coordinate', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###
